// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 16/08/2025, 01:26:19
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/bpass/Downloads/creatorflow_scaffold/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bpass/Downloads/creatorflow_scaffold/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bpass/Downloads/creatorflow_scaffold/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bpass/Downloads/creatorflow_scaffold/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bpass/Downloads/creatorflow_scaffold/frontend/plugins/**/*.{js,ts,mjs}","C:/Users/bpass/Downloads/creatorflow_scaffold/frontend/composables/**/*.{js,ts,mjs}","C:/Users/bpass/Downloads/creatorflow_scaffold/frontend/utils/**/*.{js,ts,mjs}","C:/Users/bpass/Downloads/creatorflow_scaffold/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bpass/Downloads/creatorflow_scaffold/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bpass/Downloads/creatorflow_scaffold/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/bpass/Downloads/creatorflow_scaffold/frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;